---
    - block:

        - name: ПУД1 | проверка, что файл "/etc/login.defs" есть
          become: yes
          raw: "test -f /etc/login.defs"
          failed_when: var_file_exists.rc
          register: var_file_exists
          tags:
            - pw_quality_4

        - name: ПУД1 | параметры эталонного локального пароля /etc/login.defs
          become: yes
          raw: 'egrep "^[[:space:]]*{{item[0] }}[[:space:]]+{{item[1] }}[[:space:]]*" /etc/login.defs'
          loop: "{{ login_defs_var }}"
          failed_when: var_pw_quality_active_4.rc not in [0, 1]
          register: var_pw_quality_active_4
          tags:
            - pw_quality_4

        - name: ПУД1 | проверка параметров пароля /etc/login.defs
          debug:
            msg: 
              - "  "
              - "------------------------------|||---------------------  "
              - "---->>>> {{item[0][0]}} {{'%-4s' | format(item[0][1])}} : {{ ( not item[1].rc ) | ternary('да', 'нет')}} <<<<----------------"
              - "------------------------------^^----------------------  "
              - "  "
          loop: "{{ login_defs_var[:] | zip(var_pw_quality_active_4.results) | list}}"
          loop_control:
            label: "login.defs"
          tags:
            - pw_quality_4
            - write_log

        # - name: ПУД1 | загрузка файла
        #   fetch:
        #     flat: yes
        #     dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        #     src: "/etc/login.defs"
        #   tags:
        #     - pw_quality_4

        - name: результат прохождения проверок
          set_fact:
            task_result: "{% set passed = ( ( var_pw_quality_active_4.results )[:] | map(attribute='rc') | list |  max == 0  ) %}{{passed}}"
          tags:
            - pw_quality_4/etc/security/pwquality.conf

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'pw_quality_4' %}{{ tg }}"
            task_res: "{{ task_result }}"
          tags:
            - pw_quality_4

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'pw_quality_4' %}{{ tgr }}"
          tags:
            - always