--- 
# проверка № 15
    - block:

        - name: ПУД1 | проверка, что файл "/etc/sudoers" есть
          become: yes
          raw: "test -f /etc/sudoers"
          failed_when: var_file_exists.rc
          register: var_file_exists
          tags:
            - include
            
        - name: ПУД1 | проверка наличия строки "#include/includedir /etc/sudoers"
          become: yes
          raw: " egrep '^[[:space:]]*#*[[:space:]]*(include|includedir){1}[[:space:]]*[/]{1}etc[/]{1}sudoers[.]{1}d[[:space:]]*$' '/etc/sudoers' " 
          failed_when: var_include_exists.rc not in [0, 1]
          register: var_include_exists
          tags:
            - include

        - name: ПУД1 | проверка наличия строки "#include/includedir /etc/sudoers" в sudoers
          debug: 
            msg: 
              - "Строка include/includedir есть: {{ ( not var_include_exists.rc) | ternary('Да', 'Нет')}}"          # кол-во строк
          tags:
            - include
            - write_log

        - name: ПУД1 | проверка директивы "#include/includedir /etc/sudoers"
          become: yes
          raw: "egrep '^[[:space:]]*#?(include|includedir){1}[[:space:]]*[/]{1}etc[/]{1}sudoers[.]{1}d[[:space:]]*$' '/etc/sudoers' "
          failed_when: var_include_active.rc not in [0, 1]
          register: var_include_active
          tags:
            - include

        - name: ПУД1 | проверка активности строки "#include/includedir /etc/sudoers" в sudoers
          debug: 
            msg: 
              - "Строка include/includedir НЕ активна: {{ ( var_include_active.rc ) | ternary('Да', 'Нет') }}"          # 
          tags:
            - include
            - write_log

        - name: результат прохождения проверок
          set_fact:
            task_result: "{% set passed = ( ( not var_include_exists.rc | bool ) and ( var_include_active.rc | bool )) %}{{passed}}"
          tags:
            - include

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'include' %}{{ tg }}"
            task_res: "{{ task_result }}"
          tags:
            - include

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'include' %}{{tgr}}"
          tags:
            - always