--- 
# проверка № 16

    - block:

        - name: ПУД1 | проверка, что директрия "/etc/sudoers.d" есть
          become: yes
          raw: "test -d /etc/sudoers.d"
          failed_when: var_file_exists.rc
          register: var_file_exists
          tags:
            - sudoersd

        - name: ПУД1 | проверка, что директория "/etc/sudoers.d" пустая
          become: yes
          raw: "test -z $(ls -A /etc/sudoers.d)"
          failed_when: var_dir_is_empty.rc not in [0, 1]
          register: var_dir_is_empty
          tags:
            - sudoersd

        - name: ПУД1 | проверка, что директория "/etc/sudoers.d" пустая
          debug: 
            msg: 
              - "файл sudoers.d пустой: {{ ( not var_dir_is_empty.rc ) | ternary('да', 'нет') }}"          # кол-во строк
          tags:
            - sudoersd
            - write_log

        - name: ПУД1 | запись содержимого в файл
          become: yes
          raw: "ls /etc/sudoers.d"
          failed_when: var_sudoers_output.rc not in [0, 1]
          register: var_sudoers_output
          tags:
            - sudoersd

        - name: фильтрация содержимого sudoersd
          set_fact:
            var_sudoers_content: "{{ var_sudoers_output.stdout | regex_replace('^[\\r\\n\\t]+','') | regex_replace('[\\r\\n\\t]+$','') | regex_replace('[\\r\\n\\t]+','\n') }}"
          tags:
            - sudoersd

        - name: группировка
          no_log: true
          set_fact:
            var_sudoers_ls: "{{  var_sudoers_ls | default([]) + [ item | trim ]  }}"
          with_items: "{{ (var_sudoers_content).split('\n') }}"
          tags:
            - sudoersd

        - name: ПУД1 | Содержимое /etc/sudoers.d пустая
          debug: 
            msg: 
              - "sudoers.d содержит: "         
              - "{{ var_sudoers_ls }}"          
          tags:
            - sudoersd

        # - name: save host ip
        #   become: yes
        #   shell: "echo {{ansible_ssh_host}}"
        #   register: var_host_ip
        #   tags:
        #     - sudoersd

        # - name: ПУД1 | запись содержимого в файл
        #   copy: 
        #     content: "{{ var_sudoers_output.stdout_lines }}"
        #     dest: "{{ playbook_dir }}/all_info/{{ ansible_ssh_host }}/ls_sudoersd.txt"
        #   delegate_to: localhost
        #   tags:
        #     - sudoersd

    # выгружать содержимое или список?

        - name: результат прохождения проверок
          set_fact:
            task_result: "{% set passed = ( not var_dir_is_empty.rc ) %}{{ passed }}"
          tags:
            - sudoersd

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'sudoersd' %}{{ tg }}"
            task_res: "{{ task_result }}"
          tags:
            - sudoersd

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'sudoersd' %}{{ tgr }}"
          tags:
            - always