--- 

# ПРУ 1 ausearch_file
# https://github.com/inspec/inspec/issues/768
# ausearch --input-logs 
# Use the log file location from auditd.conf as input for searching
# -sv no | success status (yes|no)

    - block:

        - name: ПРУ 3 | ----
          become: yes
          command: sort -n "{{ playbook_dir }}/files/tmp/local_user_list"  #Вывод отсортированного по алфавиту списка эталонных пользователей
          delegate_to: localhost
          register: var_get_loc_userlist # сохранение выводва в переменную
          tags:
            - ausearch_file
    # -sv no
        - name: ПРУ 3 | Регистрация попыток доступа к защищаемым файлам 
          become: yes
          raw: |
              # echo "USER __________  '{{item}}'  __________"
              echo '                                                                           '
              echo '--------------------     OPEN PASSWD SUCCESS     --------------------         '
              echo '                                                                           '
              ausearch -i --input-logs -f /etc/passwd -sc 257 -sv yes -ua $( id -u {{item}} ) | tail -n 19
              echo '                                                                           '
              echo '                                                                           '
              echo '--------------------     OPEN PASSWD FAILURE     --------------------         '
              echo '                                                                           '
              ausearch -i --input-logs -f /etc/passwd -sc 257 -sv no -ua $( id -u {{item}} ) | tail -n 19
              echo '                                                                           '
              echo '                                                                           '
              echo '--------------------     OPEN SUDOERS SUCCESS     --------------------         '
              echo '                                                                           '
              ausearch -i --input-logs -f /etc/sudoers -sc 257 -sv yes -ua $( id -u {{item}} ) | tail -n 19
              echo '                                                                           '
              echo '                                                                           '
              echo '--------------------     OPEN SUDOERS FAILURE     --------------------         '
              echo '                                                                           '
              ausearch -i --input-logs -f /etc/sudoers -sc 257 -sv no -ua $( id -u {{item}} ) | tail -n 19
              echo '                                                                           '
              echo '                                                                           '
              echo ----------------------     OPEN SHADOW SUCCESS ----------------------------
              echo '                                                                           '
              ausearch -i --input-logs -f /etc/shadow  -sc 257 -sv yes -ua $( id -u {{item}} ) | tail -n 19
              echo '                                                                           '
              echo '                                                                           '
              echo ----------------------     OPEN SHADOW FAILURE ----------------------------
              echo '                                                                           '
              ausearch -i --input-logs -f /etc/shadow  -sc 257 -sv no -ua  $( id -u {{item}} ) | tail -n 19
              echo '                                                                           '
              echo '                                                                           '
          loop: "{{var_get_loc_userlist.stdout_lines}}"
          failed_when: var_user_process.rc not in [0, 1]
          register: var_user_auth
          tags:
            - ausearch_file
            - write_log

        - name: ПРУ 3 | Регистрация попыток доступа к защищаемым файлам passwd/sudoers/shadow
          debug: 
            msg: 
              - "---------------------------------"
              - " USER  =>   '{{item.item}}'   ----"
              - "----------------------------------"
              - "{{item.stdout_lines}}"
          loop: "{{var_user_auth.results}}"
          loop_control:
            label: ""
          tags:
           - ausearch_file
           - write_log

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'ausearch_file' %}{{ tg }}"
            task_res: "executed"
          tags:
            - ausearch_file

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'ausearch_file' %}{{ tgr }}"
          tags:
            - always