---

    - name: ПРУ1 | сохранение правил ноды
      become: yes
      shell: "auditctl -l"
      changed_when: false
      failed_when: false
      # ignore_errors: true
      register: var_auditctl_user
      tags:
        - auditctl

    - name: ПРУ1 | сохранение эталонных правил
      become: yes
      shell: "cat ./files/tmp/audit_rules"
      changed_when: false
      delegate_to: localhost
      failed_when: false
      # ignore_errors: true
      register: var_auditctl_etalon
      # when:  var_auditctl_user.stdout_lines != []
      tags:
        - auditctl

    # - name: ПРУ1 | чтение swap_wipe хоста
    #   become: yes
    #   shell: "cat /etc/cron.daily/swap_wipe"
    #   changed_when: false
    #   failed_when: false
    #   # ignore_errors: true
    #   register: var_auditctl_user
    #   when: var_auditctl_user.stdout_lines != []
    #   tags:
    #     - auditctl

    - name: ПРУ1 | загрузка файла
      fetch:
        flat: yes
        dest: "{{playbook_dir}}/all_info/{{ansible_host}}/"
        src: "{{var_auditctl_user.stdout_lines > }}"
      register: var_swap_download
      # when:  var_auditctl_user.stdout_lines != []
      tags:
        - auditctl

    - name: ПРУ1 | разница правил
      debug: 
        msg:
          - "{{(var_auditctl_etalon.stdout_lines)[2:] | difference(var_auditctl_user.stdout_lines)}}"
          # - "{{var_auditctl_user.stdout}}"
          # - "{{diff }}"
      when: var_auditctl_user.stdout_lines != []
      tags:
        - auditctl
        - write_log
