--- 
# ПРУ 1 aureport

    - name: ПРУ1 | auditctl по всем пользователям 
      become: yes
      shell: "ausearch aureport -s | awk '{if($4 == 59/62) {print}}' | awk '{if($7 == {{user_uid_list}}) {print}}'"
      shell: ""
      # shell: 'ausearch -m execve -ui 1000 | aureport -f -i'
      shell: "aureport -au | tac | awk '{ if ($4~/{{item}}/ && $8~/(no|yes)/)  print }|'"
      changed_when: false
      failed_when: false
      # ignore_errors: true
      loop: "{{ lookup('file', 'files/tmp/user_list').splitlines() }}"
      register: var_user_audit
      tags:
        - aureport

    - name: ПРУ1 | печать статус auditd
      debug: 
        msg: 
          - "{{item.stdout}}"
          # - "----------------auditd status----------------"
          # - " auditd running:  {{(var_user_audit.stdout == '1') | ternary('true','false')}}"
          # - "---------------------------------------------"
      ignore_errors: true
      loop: "{{ var_user_audit.results | map(attribute='item') | list }}"
      # loop: "{{(var_user_audit)[:] | selectattr('stdout', '!=', '\'\'') | map(attribute='stdout') | list}}"
      when: var_user_audit is defined
      tags:
        - aureport
