--- 
# 10
    - name: ПРУ1 | проверка наличия logrotate в cron
      become: yes
      shell: "cat /etc/logrotate.d/syslog | grep '^[[:space:]]*/var/log/audit/audit.log[[:space:]]*$'"
      changed_when: false
      failed_when: false
      # ignore_errors: true
      register: var_logrotated
      tags:
        - logrotated

    - name: ПРУ1 | печать что директория пустая
      debug: 
        msg: 
          # - "Total rows : {{ var_allowed_user_not_in_etalon | length }}" # вывод строк не содержащихся в эталонном файле
          # - "{{ (var_string_exists.stdout_lines != []) | ternary('',  '')}}"          # кол-во строк
          # - "{{ (var_string_exists.stdout != '0') | ternary('yes',  'no')}}"          # кол-во строк
          # - "found: {{ (var_dir_is_empty.stdout != [] ) | ternary('true',  'false')}}"          # кол-во строк
          - "----------  config verification  -------------"
          - "/var/log/audit/audit.log found => {{ (var_logrotated.stdout_lines != []) | ternary('yes', 'no') }}"          # кол-во строк
          - "----------------------------------------------"
      ignore_errors: true
      when: var_logrotated is defined
      tags:
        - logrotated
        - write_log
