--- 

# ПРУ 1 статус

    - block:

        - name: ПРУ 1 | резульатат статус auditd
          become: yes
          raw: "systemctl is-active auditd || true"
          failed_when: var_status.rc
          register: var_status
          tags:
            - auditd_status

        - name: ПРУ 1 | статус auditd
          debug: 
            msg: 
              - "---------------------------------------------"
              - " статус auditd =>  {{(var_status.stdout | trim )}}"
              - "---------------------------------------------"
          tags:
            - auditd_status
            - write_log

        - name: результат прохождения проверок
          set_fact:
            task_result: "{% set passed = ( var_status.stdout | trim  ) == 'active' %}{{passed}}"
          tags:
            - auditd_status

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'auditd_status' %}{{ tg }}"
            task_res: "{{ task_result }}"
          tags:
            - auditd_status

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'auditd_status' %}{{tgr}}"
          tags:
            - always