--- 

# ПРУ 1 aureport_auth
# https://github.com/inspec/inspec/issues/1568
# ausearch --input-logs 
# Use the log file location from auditd.conf as input for searching
# -sv no | success status (yes|no)

    - block:

        - name: ПРУ1 | Сохранение списка пользователей в переменную
          become: yes
          command: sort -n "{{ playbook_dir }}/files/tmp/ad_user"  #Вывод отсортированного по алфавиту списка эталонных пользователей
          delegate_to: localhost
          register: var_get_userlist # сохранение выводва в переменную
          tags:
            - aureport_auth

        - name: ПРУ1 | Регистрация списка пользователей в переменную ad_user
          become: yes
          raw: |
              # echo "USER __________  '{{item}}'  __________"
              echo '                                                                           '
              echo '                                                                           '
              echo ---------------------------- USER_AUTH SUCCESS ----------------------------
              echo '                                                                           '
              ausearch  -i --input-logs -m USER_AUTH -sv yes -ui $( id -u {{item}} ) | tail -n 15
              echo '                                                                           '
              echo '                                                                           '
              echo ---------------------------- USER_AUTH FAILURE ----------------------------
              echo '                                                                           '
              ausearch  -i --input-logs -m USER_AUTH -sv no -ui $( id -u {{item}} ) | tail -n 15
              echo '                                                                           '
              echo '                                                                           '
              echo '         --------------------     USER_END     --------------------         '
              echo '                                                                           '
              ausearch   -i --input-logs -m USER_END -ui $( id -u {{item}} ) | tail -n 15
          loop: "{{var_get_userlist.stdout_lines}}"
          failed_when: var_user_auth.rc not in [0, 1] 
          register: var_user_auth
          tags:
            - aureport_auth
            - write_log

        - name: ПРУ1 | Регистрация попыток входа/выхода из списка пользователей ad_user
          debug: 
            msg: 
              - "---------------------------------"
              - " USER  =>   '{{item.item}}'   ----"
              - "----------------------------------"
              - "{{item.stdout_lines}}"
          loop: "{{var_user_auth.results}}"
          loop_control:
            label: ""
          tags:
           - aureport_auth
           - write_log

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'aureport_auth' %}{{ tg }}"
            task_res: "executed"
          tags:
            - aureport_auth

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'aureport_auth' %}{{ tgr }}"
          tags:
            - always