#!/bin/bash

swap_used=`free -m | grep Swap | awk '{print $3}'`
mem_free=`free -m | grep Mem | awk '{print $4}'`

if [ $swap_used -lt $mem_free -a $swap_used -gt 0 ]; then
    swapoff -a; swapon -a
    echo `date "+%x %T"`": Swap switched (Swap used/Mem free - $swap_used/$mem_free)"
else
    echo `date "+%x %T"`": Switching swap is impossible or not needed (Swap used/Mem free - $swap_used/$mem_free)"
fi
