--- 
# ПУД 2 

    - block:

        - name: ПУД2 | СОХРАНЕНИЕ СПИСКА IP
          shell: 'cat files/tmp/ip_list | egrep -oE "^[[:space:]]*([0-9]{1,3}\.){3}[0-9]{1,3}[[:space:]]*$"'
          delegate_to: localhost
          register: ip_list
          tags:
            - ss

        - name: ПУД2 | запись ssh соединения
          become: yes
          raw: "ss -n -at '( sport = :22 )' | awk 'match($5, /{{item}}.*/) {print}' | egrep '[^[:space:]]'"
          loop: "{{ ip_list.stdout_lines }}"
          failed_when: var_ssh_peer.rc not in [0, 1]
          register: var_ssh_peer
          tags:
            - ss

        - name: группировка 1
          no_log: true
          set_fact:
            var_ss_hosts: "{{ var_ss_hosts | default([]) + [ item.stdout | trim ] | select() }}"
          with_items: "{{ (var_ssh_peer.results) }}"
          tags:
            - ss

        - name: группировка 2
          no_log: true
          set_fact:
            var_ss_filt: "{{ var_ss_filt | default([]) + [ item.splitlines() ] | flatten }}"
          with_items: "{{ (var_ss_hosts) }}"
          tags:
            - ss

        - name: ПУД2 | вывод сетевых соединений 
          debug: 
            msg: 
              - "--------------ssh connections----------------"
              - "{{ var_ss_filt }}"
              - "---------------------------------------------"
          when: var_ssh_peer is defined
          tags:
            - ss
            - write_log 

        - name: результат прохождения проверок
          set_fact:
            task_result: "{% set passed = ( ( var_ssh_peer.results )[:] | map(attribute='rc') | list |  max == 0   ) %}{{ passed }}"
          tags:
            - ss

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'ss' %}{{ tg }}"
            task_res: "{{ task_result }}"
          tags:
            - ss
            
      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'ss' %}{{tgr}}"
          tags:
            - always
