---

    - name: ПР | файл есть
      become: yes
      stat: path=/etc/pam.d/common-password
      register: var_exists
      failed_when: not var_exists.stat.exists
      tags:
        - pr_password_quality_2

    - name: ПР | проверка совпадения с эталоном строк 
      become: yes
      shell: "{{pam_unix_2}}"
      register: var_passwords_active
      tags:
        - pr_password_quality_2

    - name: ПР | проверка наличия и активности локальных параметров пароля в /etc/pam.d/common-password
      debug: 
        msg: 
          - "  "
          - "----------------------------------------------------  "
          - "-- строка присутствует => {{(not (var_passwords_active.rc)) | ternary('да', 'нет')}}"
          - "----------------------------------------------------  "
      tags:
        - pr_password_quality_2
        - write_log

    - name: ПР | эталонные значения параметров
      become: yes
      shell: "echo {{var_passwords_active.stdout}} | egrep {{params_regex}}"
      loop: "{{profile_common_password_var}}"
      when: var_passwords_active.stdout != ''
      register: var_passwords_params
      tags:
        - pr_password_quality_2

    - name: ПР | проверка совпадения параметров локального пароля с эталонным значением
      debug: 
        msg: 
          - "  "
          - "----------------------------------------------------  "
          - "-->> '{{ (item.0)[:] | join(' ') }}' => {{(item.1.stdout != '') | ternary('да', 'нет')}}              "
          - "----------------------------------------------------  "
      loop: "{{(profile_common_password_var) | zip(var_passwords_params.results) | list}}"
      when: var_passwords_active.stdout != ''
      tags:
        - pr_password_quality_2
        - write_log


    - name: ПР | загрузка файла /etc/pam.d/common-password
      fetch:
        flat: yes
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/pam.d/common-password"
      tags:
        - pr_password_quality_2

      
    - name: summary +
      shell: "printf '%-20s %15s\n' 'pr_password_quality_2 => ' {{('нет' in ad_group_list.results.stdout_lines[:]) | ternary('1', '0')}} | tee -a  {{log_var}}"
      delegate_to: localhost
      tags:
        - alway