--- 
# ПУД 2  Red Hat Enterprise Linux

    - name: ПУД2 | запись сетевых содинений
      become: yes
      shell: "netstat –n (ss –n | tail - 30)"
      changed_when: false
      failed_when: false
      # ignore_errors: true
      register: var_network_connection
      tags:
        - disk_partitioning

    - name: ПУД2 | печать сетевых содинений
      debug: 
        msg: 
          # - "Total rows : {{ var_allowed_user_not_in_etalon | length }}" # вывод строк не содержащихся в эталонном файле
          # - "{{ (var_string_exists.stdout_lines != []) | ternary('',  '')}}"          # кол-во строк
          # - "{{ (var_string_exists.stdout != '0') | ternary('yes',  'no')}}"          # кол-во строк
          # - "found: {{ (var_dir_is_empty.stdout != [] ) | ternary('true',  'false')}}"          # кол-во строк
          - "{{ (var_network_connection.stdout_lines)}}"          # кол-во строк
      ignore_errors: true
      when: var_network_connection is defined
      tags:
        - disk_partitioning
# Password20