--- 
# ПРУ 1
# ausearch --input-logs 
# Use the log file location from auditd.conf as input for searching
# -sv no | success status (yes|no)

    - name: ПРУ1 | проверка налачия логов старше 90 дней от текущей даты
      become: yes
      shell: "ausearch --input-logs --end $(date --date='90 days ago'  +'%m/%d/%Y') | tail -n 15"
      changed_when: false
      failed_when: false
      register: var_logs_before
      tags:
        - logs_time

# #  - проверка каждого пользователя на попытку аутентификации 
    # - name: ПУД1 | Сохранение списка пользователей в переменную
    #   become: yes
    #   shell: 'ausearch -m USER_AUTH | grep  -B 1 {{item}} | grep -B 1 failed'
    #    # ausearch -m USER_AUTH | grep  -B 1 {{item}} | grep -B 1 success | tail -n 15
    #    # ausearch -m USER_END | grep  -B 1 {{item}} tail -n 15
    #   # loop: "{{var_get_userlist.stdout_lines}}"
    #   register: var_logs_before
    #   tags:
    #     - logs_time

#     - name: ПРУ1 | сохранение aureport аутнетфикаций 
#       become: yes
#       changed_when: false
#       failed_when: false
#       # ignore_errors: true
#       loop: "{{ lookup('file', 'files/tmp/user_list').splitlines() }}"
#       register: var_user_audit
#       tags:
#        - logs_time

    - name: ПРУ1 | печать пользователей
      debug: 
        msg: 
          - "------ Логи старше 90 дней есть: {{(var_logs_before.stdout_lines != []) | ternary('да','нет')}} ------------------"
          - "----------------------------------"
          - "----------- пример если есть ---------------"
          - "{{var_logs_before.stdout_lines}}"
      ignore_errors: true
      # loop: "{{ | debug}}"
      # loop: "{{var_logs_before}}"
      # loop: "{{(var_user_audit)[:] | selectattr('stdout', '!=', '\'\'') | map(attribute='stdout') | list}}"
      # when: var_get_userlist is defined
      tags:
       - logs_time

    # - name: ПРУ1 | печать пользователей
    #   debug: 
    #     msg: 
    #       - "{{var_get_userlist.stdout_lines}}"
    #       # - "----------------auditd status----------------"
    #       # - " auditd running:  {{(var_user_audit.stdout == '1') | ternary('true','false')}}"
    #       # - "---------------------------------------------"
    #   ignore_errors: true
    #   # loop: "{{var_get_userlist.results}}"
    #   # loop: "{{(var_user_audit)[:] | selectattr('stdout', '!=', '\'\'') | map(attribute='stdout') | list}}"
    #   when: var_get_userlist is defined
    #   tags:
    #    - logs_time
