    - name: Сбор /etc/passwd
      shell: if test -f "/etc/passwd" ; then /bin/true; else /bin/false; fi
      register: result
      ignore_errors: True
      tags:
       - fetch_files

    - name: fetch stat +
      shell: "printf 11111 | tee -a ./all_info/{{ansible_host}}/logs/sum_{{ansible_host}}.txt"
      delegate_to: localhost
      when: result is failed
      tags:
        - fetch_files

    - name: ПУД1 | загрузка файла /etc/passwd
      fetch:
        flat: yes
        validate_checksum: true
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/passwd"
      register: result_fetch
      when: result is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-20s %15s\n' '/etc/passwd => ' 'true' | tee -a {{./all_info/{{ansible_host}}/logs/sum_{{ansible_host}}.txt}}"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-20s %15s\n' '/etc/passwd => ' 'error' | tee -a {{./all_info/{{ansible_host}}/logs/sum_{{ansible_host}}.txt}}"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is failed
      tags:
        - fetch_files
