---
    - block:

        - name: ПР | проверка, что файл "/etc/pam.d/common-auth" есть
          become: yes
          raw: "test -f /etc/pam.d/common-auth"
          failed_when: var_file_exists.rc
          register: var_file_exists
          tags:
            - pr_password_quality_3

        - name: ПР | эталонные значения параметров
          become: yes
          raw: "egrep {{params_regex_v2}} /etc/pam.d/common-auth"
          loop: "{{profile_common_auth_var}}"
          failed_when: var_passwords_params.rc not in [0, 1]
          register: var_passwords_params
          tags:
            - pr_password_quality_3

        - name: ПР | проверка совпадения параметров входа/выхода с эталонным значением
          debug: 
            msg: 
              - "  "
              - "----------------------------------------------------  "
              - " '{{ (item.0)[:] | join(' ') }}' => {{(not item.1.rc) | ternary('да', 'нет')}}             "
              - "----------------------------------------------------  "
          loop: "{{(profile_common_auth_var) | zip(var_passwords_params.results) | list}}"
          loop_control:
            label: ""
          tags:
            - pr_password_quality_3
            - write_log

        - name: результат прохождения проверок
          set_fact:
            task_result: "{% set passed = ( ( var_passwords_params.results )[:] | map(attribute='rc') | list |  max == 0  ) %}{{passed}}"
          tags:
            - pr_password_quality_3

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'pr_password_quality_3' %}{{ tg }}"
            task_res: "{{ task_result }}"
          tags:
            - pr_password_quality_3

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'pr_password_quality_3' %}{{ tgr }}"
          tags:
            - always