--- 
# --------------   Astra    -----------------
# - name: main tasks
#   hosts: local 
#   gather_facts: false 
#   ignore_errors: true
#   remote_user: ansibenode
#   become: yes
#   become_method: sudo
#     pre_tasks:
  
- name: main tasks
  hosts: all 
  gather_facts: true 
  ignore_errors: true
  # remote_user: ansibenode
  become: yes
  become_method: sudo
  # remote_user: root
  pre_tasks:
    - name: logging settings update
      shell: 'find . -maxdepth 1 -name "*$(date +%Y%m%d_%H%M)*" | sed -i -r "s/^(log_path =).*/\1 $(echo "ansible_$(date "+%Y%m%d_%H%M")_$(wc -l).log")/" ansible.cfg' #запись имени лога с датой и временем запуска PLAYBOOK в конфигурационном файле (меняет имя лога в ansible.cfg)
      delegate_to: localhost
      # run_once: true
      # remote_user: root
      tags:
        - always # запуск независимо от тега

    - name: ansible
      debug:
        msg:
          - "{{ansible_os_family}}"

  # roles:
  #   - oracle
  tasks:

    - name: oracle
      import_role:
        name: "oracle"
      when: ansible_os_family.startswith('Astra Linux') # переменные для Astra Linux

    - name: lubuntu
      import_role:
        name: "oracle"
      when: ansible_os_family.startswith('Debian') # переменные для Astra Linux
