---
    - name: ПУД1 формируем список непустых групп пользователей
      # shell: 'getent group |cut -d: -f1 | sort -n ' # старая
      shell: 'getent group | egrep -v "^.+:.+:.+:$"  | sort -n ' # все с не пустым 4-м полем
      changed_when: no
      failed_when: false
      register: var_get_grouplist
      tags:
        - loc_group_list

    # - name: ПУД1 Вывод списка групп пользователей
    #   debug:
    #     msg: "{{ var_get_grouplist.stdout_lines  }}"
    #   ignore_errors: true
    #   tags:
    #     - loc_group_list

    - name: ПУД1 Сохраниение эталонного списка групп в переменную
      become: yes
      command: sort -n "{{ playbook_dir }}/files/tmp/group_list"  # Вывод отсортированного по алфавиту списка групп эталонных пользователей
      delegate_to: localhost
      changed_when: false
      failed_when: false
      ignore_errors: true 
      register: var_get_grouplist_etalon # сохранение выводва в переменную
      tags:
        - loc_group_list

    # - name: ПУД1 Вывод эталонного списка групп пользователей
    #   debug:
    #     msg: "{{ var_get_grouplist_etalon.stdout_lines }}"
    #   ignore_errors: true
    #   tags:
    #     - loc_group_list

    - name: ПУД1 | Сохранение содержимого "переменных списков групп" в виде списка
      become: yes
      set_fact:
        # verfication_grouplist: "{{ var_get_grouplist.stdout_lines }}"    # список - список пользователей | для сравнения с помощью встроенной функции "difference"(список - 
        # etalon_grouplist: "{{ var_get_grouplist_etalon.stdout_lines }}"  # список - эталонный список    | стркутура данных вроде массива, в данном случае массива строк) 
        # var_usergroup_not_in_etalon: "{{ var_get_grouplist.stdout_lines | difference(var_get_grouplist_etalon.stdout_lines)}}" # старая
        var_usergroup_not_in_etalon: "{{ (var_get_grouplist.stdout_lines )}}" # строки "списка пользователей" НЕ содержащиеся в "эталоном списке"
      tags:
        - loc_group_list

    - name: ПУД1 | Вывод локальных групп НЕ содержащихся в эталонном списке групп group_list
      debug: 
        msg: 
          # - "Total rows : {{ var_usergroup_not_in_etalon | length }}" # вывод строк не содержащихся в эталонном файле
          - "     "
          - "--------------------------------------------------"
          - "{{ var_usergroup_not_in_etalon }}"          # 
          - "--------------------------------------------------"

      ignore_errors: true
      when: var_get_grouplist # исполнение TASK, если "cписок групп пользователей" не пустой
      tags:
        - loc_group_list
        - write_log

    - name: ПУД1 | загрузка файла
      fetch:
        flat: yes
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/group"
      tags:
        - loc_group_list