---

    - name: ПУД1 | проверка наличия группы wheel
      become: да
      shell: "getent group | cut -d: -f1 | if egrep -q ^wheel$ ; then echo да ; else echo нет ; fi"
      changed_when: false
      failed_when: false
      ignore_errors: true
      register: var_group_exists
      tags:
        - wheel_2

    - name: ПУД1 | проверка наличия группы wheel
      debug: 
        msg: 
          - "найдена группа wheel: {{ (var_group_exists.stdout) }}"          # есть/нет пользователи
      ignore_errors: true
      when: var_group_exists is defined
      tags:
        - wheel_2
        - write_log


    - name: ПУД1 | проверка отсутствия пользователей в группе wheel
      become: да
      shell: "getent group | grep ^wheel:* | cut -d: -f4 | if egrep -q ^[[:space:]]*$; then echo да; else echo нет; fi" 
      changed_when: false
      failed_when: false
      ignore_errors: true
      register: var_group_empty
      when: var_group_exists.stdout != 'нет'
      tags:
        - wheel_2

    - name: ПУД1 | проверка отсутствия пользователей в группе wheel
      become: да
      shell: "getent group | grep ^wheel:* | cut -d: -f4" 
      changed_when: false
      failed_when: false
      ignore_errors: true
      register: var_group_empty_users
      when: var_group_exists.stdout != 'нет'
      tags:
        - wheel_2

    - name: ПУД1 | проверка отсутствия пользователей в группе wheel
      become: да
      debug: 
        msg: 
          - "группа wheel пустая: {{ (var_group_empty.stdout) }}" # вывод наличия пользователей в группе wheel
          - "пользователи группы wheel: {{ (var_group_empty_users.stdout) }}" # вывод наличия пользователей в группе wheel
      ignore_errors: true
      when: var_group_exists.stdout != 'нет'
      tags:
        - wheel_2
        - write_log
        
    - name: ПУД1 | загрузка файла
      fetch:
        flat: да
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/pam.d/su"
      tags:
        - wheel_2

    - name: summary +
      shell: "printf '%-20s %15s\n' 'wheel_2 => ' {{(var_group_exists.stdout != 'нет') | ternary( (var_group_empty is defined) |ternary('1', '0'), '0')}} | tee -a {{log_var}}"
      delegate_to: localhost
      tags:
        - always