--- 
# ПУД 2 apache ss

    - name: ПУД2 | СОХРАНЕНИЕ СПИСКА IP
      shell: 'cat files/tmp/ip_list | egrep  -oE "^[[:space:]]*([0-9]{1,3}\.){3}[0-9]{1,3}[[:space:]]*$"'
      delegate_to: localhost
      register: ip_list
      tags:
        - ss
   
    - name: ПУД2 | запись ssh соединения
      become: yes
      shell: "ss -n -at '( sport = :22 )' | awk ' match($5, /{{item}}.*/) {print}'"
      changed_when: false
      failed_when: false
      loop: "{{ip_list.stdout_lines}}"
      # ignore_errors: true
      register: var_ssh_peer
      tags:
        - ss

    - name: ПУД2 | печать сетевых соединений 
      debug: 
        msg: 
          - "--------------ssh conections-----------------"
          - "{{ ((var_ssh_peer.results)[:] | selectattr('stdout', '!=', '\'\'') | map(attribute='stdout') | list ) }}"
          - "---------------------------------------------"
      ignore_errors: true
      when: var_ssh_peer is defined
      tags:
        - ss
