---

    - name: ПУД1 | save "наличие строки default_realm = ROSNEFT.RU"
      become: yes
      shell: 'if egrep -q "^[[:space:]]*#*[[:space:]]*default_realm[[:space:]]*=[[:space:]]*ROSNEFT\.RU[[:space:]]*$" /etc/krb5.conf; then echo да; else echo нет; fi'
      changed_when: false
      failed_when: false
      ignore_errors: true
      register: var_pswd
      tags:
        - pswd


    - name: ПУД1 | проверка наличия строки "default_realm = ROSNEFT.RU"
      debug: 
        msg: 
          - "  "
          - "----------------------------------------------------  "
          - "[default_realm = ROSNEFT.RU] существует => {{var_pswd.stdout}}         "          # кол-во строк
          - "----------------------------------------------------  "
          # - "  "
      ignore_errors: true
      when: var_pswd is defined
      tags:
        - pswd
        - write_log

    # - name: проверка активности если существует
      # block:

    - name: ПУД1 | проверка "активности строки default_realm = ROSNEFT.RU"
      become: yes
      shell: 'if egrep -q "^[[:space:]]*default_realm[[:space:]]*=[[:space:]]*ROSNEFT\.RU[[:space:]]*$" /etc/krb5.conf; then echo да; else echo нет; fi'
      changed_when: false
      failed_when: false
      ignore_errors: true
      register: var_pswd_active
      tags:
        - pswd

    - name: ПУД1 | save krb5.conf
      become: yes
      shell: 'grep "^[[:space:]]*default_realm[[:space:]]*=.*$" /etc/krb5.conf'
      changed_when: false
      failed_when: false
      ignore_errors: true
      register: var_pswd_value
      tags:
        - pswd

    - name: ПУД1 | проверка активности строки "default_realm = ROSNEFT.RU"
      debug: 
        msg: 
          - "  "
          - "-----------------------------------------------------  "
          - "[default_realm = ROSNEFT.RU] активна => {{var_pswd_active.stdout}}           "          # кол-во строк
          - "-----------------------------------------------------  "
          # - "  "
      ignore_errors: true
      when: var_pswd is defined
      tags:
        - pswd
        - write_log
      # when: var_pswd.stdout == 'да'
    

    - name: ПУД1 | загрузка файла /etc/krb5.conf
      ignore_errors: true
      fetch:
        flat: yes
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/krb5.conf"
      tags:
        - pswd

    - name: summary +
      shell: "printf '%-20s %15s\n' 'pswd => ' {{(var_pswd.stdout == 'да') | ternary((var_pswd_active.stdout == 'да') | ternary('1', '0'), '0')}} | tee -a {{log_var}}"
      delegate_to: localhost
      tags:
        - always