--- 
# ПУД 4 матрица доступов

    - name: ПУД4 | резульатат getfacl
      become: yes
      shell:
        cmd: |
          echo ----------------------------getfacl /etc/passwd ----------------------------
          getfacl /etc/passwd
          echo ---------------------------- getfacl /etc/shadow ----------------------------
          getfacl /etc/shadow
          echo ---------------------------- getfacl /var/log/audit ----------------------------
          getfacl /var/log/audit
      changed_when: false
      failed_when: false
      # ignore_errors: true
      register: var_getfacl
      tags:
        - getfacl

    - name: ПУД4 | Проверка прав доступа на защищаемые объекты
      debug: 
        msg: 
          - "{{var_getfacl.stdout_lines}}"
      ignore_errors: true
      tags:
       - getfacl
       - write_log
