---

    - name: ПУД1 | сбор инфы по Астре
      become: yes
      script: "echo {{item}}"
      changed_when: false
      failed_when: false
      ignore_errors: true
      loop:
        - "{{ lookup('file', './Astra.txt').splitlines() }}"
      register: var_info_gathering
      tags:
        - info_gathering


    - name: ПУД1 | печать наличия группы wheel
      debug: 
        msg: 
          # - "Total rows : {{ var_allowed_user_not_in_etalon | length }}" # вывод строк не содержащихся в эталонном файле
          # - "{{ (var_group_exists.stdout_lines != []) | ternary('',  '')}}"          # кол-во строк
          # - "{{ (var_group_exists.stdout != '0') | ternary('yes',  'no')}}"          # кол-во строк
          - "{{ (var_info_gathering) }}"          # кол-во строк
      ignore_errors: true
      loop: "{{var_info_gathering.results}}"
      when: var_info_gathering is defined
      tags:
        - info_gathering