---

    - name: ПРУ5 | Получение времени последнего времени актуализции базы данных вирусных сигнатур
      become: yes
      shell: "$(echo /opt/kaspersky/kesl/bin/kesl-control --app-info) | egrep -i '^[[:space:]]*Защита[[:space:]]*от[[:space:]]*файловых[[:space:]]*угроз:[[:space:]]*Задача[[:space:]]*доступна[[:space:]]*и[[:space:]]*выполняется[[:space:]]*$'"
      changed_when: false
      failed_when: false
      ignore_errors: true
      no_log: true
      register: var_ksn
      tags:
        - ksn_synch

    - name: ПРУ5 | Печать "время последней актуализации БД вирусных сигнатур"
      debug:
        msg: 
          - "     "
          - "--------------------- активность ФЗ --------------------"
          - " ФЗ активна {{(var_ksn.stdout_lines != []) | ternary('да', 'нет') }}"
          - "--------------------------------------------------------"
      ignore_errors: true
      tags:
        - ksn_synch


    # - name: ПРУ5 | загрузка файла /etc/sssd/sssd.conf
    #   fetch:
    #     flat: yes
    #     dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
    #     src: "/etc/sssd/sssd.conf"
    #   tags:
    #     - ksn_synch


    - name: summary +
      shell: "printf '%-20s %15s\n' 'ksn_synch => ' {{(var_ksn.stdout_lines != []) | ternary('1', '0')}} | tee -a  {{log_var}}"
      delegate_to: localhost
      tags:
        - always