--- 
# ПУД 3  
    - block:

        - name: ПУД3 |fdisk
          become: yes
          raw: "fdisk -l"
          failed_when: var_fdisk.rc not in [0, 1]
          register: var_fdisk
          tags:
            - fdisk

        - name: ПУД3 | печать fdsik
          debug: 
            msg: 
              - "{{ (var_fdisk.stdout_lines)}}"          # кол-во строк
          when: var_fdisk is defined
          tags:
            - fdisk

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'fdisk' %}{{ tg }}"
            task_res: "executed"
          tags:
            - fdisk

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'fdisk' %}{{tgr}}"
          tags:
            - always
