---

    - name: ПРУ5 | Проверка aide_cron в cron.daily
      become: yes
      shell: "ls /etc/cron.daily/ | more | grep ^aide_cron$"
      changed_when: false
      failed_when: false
      ignore_errors: true
      no_log: true
      register: var_aide_conf
      tags:
        - aide_conf

    - name: ПРУ5 | Вывод списка пользователей в sssd с разрешённым входом
      debug:
        msg: 
          - "     "
          - "--------------------- активность ФЗ --------------------"
          - " ФЗ активна {{(var_aide_cron.stdout_lines != []) | ternary('да', 'нет') }}"
          - "--------------------------------------------------------"
      ignore_errors: true
      tags:
        - aide_conf
        - write_log


    - name: ПРУ5 | загрузка файла /etc/sssd/sssd.conf
      fetch:
        flat: yes
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/aide.conf"
      tags:
        - aide_conf


    - name: summary +
      shell: "printf '%-20s %15s\n' 'ksn => ' {{(var_aide_cron.stdout_lines != []) | ternary('1', '0')}} | tee -a  {{log_var}}"
      delegate_to: localhost
      tags:
        - aide_c