--- 
# ПУД 4 матрица доступов
    - block:

        - name: ПУД 4 | проверка, что файл "/etc/passwd" есть
          become: yes
          raw: "test -f /etc/passwd"
          failed_when: var_file_exists.rc
          register: var_file_exists
          tags:
            - getfacl

        - name: ПУД 4 | проверка, что файл "/etc/shadow" есть
          become: yes
          raw: "test -f /etc/shadow"
          failed_when: var_file_exists.rc
          register: var_file_exists
          tags:
            - getfacl

        - name: ПУД 4 | проверка, что файл "/var/log/audit" есть
          become: yes
          raw: "test -f /var/log/audit"
          failed_when: var_file_exists.rc
          register: var_file_exists
          tags:
            - getfacl
            
        - name: ПУД 4 | резульатат getfacl
          become: yes
          raw: |
              echo ----------------------------getfacl /etc/passwd ----------------------------
              getfacl /etc/passwd
              echo ---------------------------- getfacl /etc/shadow ----------------------------
              getfacl /etc/shadow
              echo ---------------------------- getfacl /var/log/audit ----------------------------
              getfacl /var/log/audit
          failed_when: var_getfacl.rc not in [0, 1]
          register: var_getfacl
          tags:
            - getfacl

        - name: ПУД 4 | Проверка прав доступа на защищаемые объекты
          debug: 
            msg: 
              - "{{var_getfacl.stdout_lines}}"
          ignore_errors: true
          tags:
           - getfacl
           - write_log

        # - name: summary +
        #   shell: "printf '%-20s %15s\n' 'getfacl => ' 'executed'| tee -a  {{log_var}}"
        #   delegate_to: localhost
        #   tags:
        #     - always

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'getfacl' %}{{ tg }}"
            task_res: "executed"
          tags:
            - getfacl

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'getfacl' %}{{tgr}}"
          tags:
            - always
