--- 
# ПУД 3  

    - name: ПУД3 |ps
      become: yes
      shell: "ps -ef | more "
      changed_when: false
      failed_when: false
      # ignore_errors: true
      register: var_ps
      tags:
        - ps

    - name: ПУД3 | печать fdsik
      debug: 
        msg: 
          # - "Total rows : {{ var_allowed_user_not_in_etalon | length }}" # вывод строк не содержащихся в эталонном файле
          # - "{{ (var_string_exists.stdout_lines != []) | ternary('',  '')}}"          # кол-во строк
          # - "{{ (var_string_exists.stdout != '0') | ternary('yes',  'no')}}"          # кол-во строк
          # - "found: {{ (var_dir_is_empty.stdout != [] ) | ternary('true',  'false')}}"          # кол-во строк
          - "{{ (var_ps.stdout_lines)}}"          # кол-во строк
      ignore_errors: true
      when: var_ps is defined
      tags:
        - ps
