--- 
# проверка № 16

    - name: ПУД1 | проверка, что файл securetty пуст
      become: yes
      shell: "cat /etc/securetty | if wc -l; then echo no; else echo yes; fi"
      changed_when: false
      failed_when: false
      # ignore_errors: true
      register: var_file_is_empty
      tags:
        - securetty

    - name: ПУД1 | печать что директория пустая
      debug: 
        msg: 
          - "---------------------------------------------------"
          - "/etc/securetty is empty: {{ (var_file_is_empty.stdout_lines[0] == '0' ) | ternary('yes',  'nope')}}"
          - "---------------------------------------------------"
      ignore_errors: true
      when: var_file_is_empty is defined
      tags:
        - securetty

    - name: ПУД1 | запись содержимого в файл
      become: yes
      shell: "cat /etc/securetty"
      changed_when: false
      failed_when: false
      # ignore_errors: true
      register: var_securetty_output
      tags:
        - securetty

    # - name: ПУД1 | печать что директория пустая
    #   debug: 
    #     msg: 
    #       - "---------------------------------------------------"
    #       - "/etc/securetty content: "
    #       - "{{ (var_securetty_output.stdout_lines) }}"
    #       - "---------------------------------------------------"
    #   ignore_errors: true
    #   when: var_file_is_empty is defined
    #   tags:
    #     - securetty

    - name: save host ip
      become: yes
      shell: "echo {{ansible_ssh_host}}"
      register: var_host_ip
      tags:
        - securetty

    - name: ПУД1 | запись содержимого в файл
      copy: 
        content: "{{var_securetty_output.stdout_lines}}"
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/securetty.txt"
      delegate_to: localhost
      tags:
        - securetty

    - name: summary +
      shell: "printf '%-20s %15s\n' 'securetty => ' {{(var_securetty_output.stdout_lines == []) | ternary('1', '0')}} | tee -a  {{log_var}}"
      delegate_to: localhost
      tags:
        - always