---
    - name: ПУД1 Сохранить список групп с разрешённым входом
      become: yes
      shell: "grep ^simple_allow_groups /etc/sssd/sssd.conf | sed 's/^.*=//' | tr ',' '\n' | tr -d ' \r\t' | sort -n"
      changed_when: false
      failed_when: false
      ignore_errors: true
      register: var_get_allowed_group
      tags:
        - ad_group_list

    - name: ПУД1 Вывод списка групп с разрешённым входом
      debug:
        msg: 
          - "     "
          - "------------------список групп--------------------"
          - "{{ var_get_allowed_group.stdout_lines  }}"
          - "--------------------------------------------------"
      ignore_errors: true
      tags:
        - ad_group_list

    - name: ПУД1 Сохранение эталонного списка групп с разрешённым входом
      become: yes
      # путь к файлу прописать!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      # >>>>>>>>>>>>>>>>|||||||||||||||||||||||||||||||||||||||<<<<<<<<<
      command: sort -n "{{ playbook_dir }}/files/tmp/ad_group"  # отсортированного по алфавиту списка эталонных групп
      changed_when: false
      failed_when: false
      # файл на контроллере
      delegate_to: localhost
      ignore_errors: true 
      register: var_get_allowed_group_etalon # сохранение вывода в переменную
      tags:
        - ad_group_list

    # - name: ПУД1 Вывод эталонного списка списка групп с разрешённым входом
    #   debug:
    #     msg: "{{ var_get_allowed_group_etalon.stdout_lines }}"
    #   ignore_errors: true
    #   tags:
    #     - ad_group_list

    - name: ПУД1 | Сохранение содержимого "переменных списков" в виде списка
      become: yes
      set_fact:
        # verification_list: "{{ var_get_userlist.stdout_lines }}"
        # etalon_list: "{{ var_get_userlist_etalon.stdout_lines }}"
        var_allowed_group_not_in_etalon: "{{ var_get_allowed_group.stdout_lines | difference(var_get_allowed_group_etalon.stdout_lines)}}" # строки "списка разрешенных групп" НЕ содержащиеся в "эталоном списке разрешённых"
      tags:
        - ad_group_list
  
    - name: ПУД1 | Вывод строк НЕ содержащихся в эталонном списке
      debug: 
        msg: 
          # - "Total rows : {{ var_allowed_group_not_in_etalon | length }}" # вывод строк не содержащихся в эталонном файле
          - "     "
          - "---------------не эталонные группы----------------"
          - "{{ var_allowed_group_not_in_etalon }}"          # кол-во строк
          - "--------------------------------------------------"
      ignore_errors: true
      when: var_get_allowed_group # исполнение TASK, если "cписок групп" не пустой
      tags:
        - ad_group_list

    - name: ПУД1 | загрузка файла /etc/sssd/sssd.conf
      fetch:
        flat: yes
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/sssd/sssd.conf"
      tags:
        - ad_group_list
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------