--- 
# 13

    - name: ПУД1 | проверка сбор активных пользователей
      become: yes
      # shell: 'getent shadow | grep "^[^:]*:.\?:" | cut -d: -f1'
      shell: 'getent passwd | grep "bash" | cut -d: -f1 | sort -n '
      changed_when: false
      failed_when: false
      # ignore_errors: true
      register: var_passwords_set_1
      tags:
        - pw_quality_3

    - name: ПУД1 | проверка сбор аткивных УЗ без без заданного пароля
      become: yes
      # shell: 'getent shadow | grep "^[^:]*:.\?:" | cut -d: -f1'
      shell: 'cat /etc/shadow | egrep "^{{item}}:[\*\!]:" '
      changed_when: false
      failed_when: false
      loop: "{{var_passwords_set_1.stdout_lines}}"
      # ignore_errors: true
      register: var_passwords_set
      tags:
        - pw_quality_3

    - name: ПУД1 | печать "на всех активных УЗ задан пароль"
      debug: 
        msg: 
          - "-----------------------------{{'\\|||/'}}-----------------------  "
          - " На всех активных УЗ пароль => {{ (var_passwords_set.results)[:] | map(attribute='rc') | list | min | ternary('да, внизу должно быть пусто', 'нет, список внизу')}}            "
          - '----------------{{ "Активные УЗ без пароля" }}--------------------  '
          - "{{ (var_passwords_set.results)[:] | selectattr('stdout', '!=', '\'\'') | map(attribute='stdout') | list }}"
          - "----------------------------------------------------------  "
          # - "  "
      loop: 
      # when:  not item.rc 
      ignore_errors: true
      # when: var_passwords_set is defined
      tags:
        - pw_quality_3
        # - print_action

    - name: ПУД1 | загрузка файла shadow
      fetch:
        flat: yes
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/shadow"
      tags:
        - pw_quality_3