--- 
# проверка № 16

    - name: ПУД1 | проверка, что директория пустая
      become: yes
      shell: "ls /etc/sudoers.d | if wc -l; then echo no; else echo yes; fi"
      changed_when: false
      failed_when: false
      # ignore_errors: true
      register: var_dir_is_empty
      tags:
        - sudoersd

    - name: ПУД1 | печать что директория пустая
      debug: 
        msg: 
          - "sudoers.d is empty: {{ (var_dir_is_empty.stdout_lines[0] == '0' ) | ternary('yes',  'nope')}}"          # кол-во строк
      ignore_errors: true
      when: var_dir_is_empty is defined
      tags:
        - sudoersd


    - name: ПУД1 | запись содержимого в файл
      become: yes
      shell: "ls /etc/sudoers.d"
      changed_when: false
      failed_when: false
      # ignore_errors: true
      register: var_sudoers_output
      tags:
        - sudoersd

    - name: ПУД1 | печать что директория пустая
      debug: 
        msg: 
          - "sudoers.d content: "          # кол-во строк
          - "{{ (var_sudoers_output.stdout) }}"          # кол-во строк
      ignore_errors: true
      when: var_dir_is_empty is defined
      tags:
        - sudoersd

    - name: save host ip
      become: yes
      shell: "echo {{ansible_ssh_host}}"
      register: var_host_ip
      tags:
        - sudoersd

    - name: ПУД1 | запись содержимого в файл
      copy: 
        content: "{{var_sudoers_output.stdout}}"
        dest: "{{playbook_dir}}/all_info/{{var_host_ip.stdout}}/ls_sudoersd.txt"
      delegate_to: localhost
      tags:
        - sudoersd

# выгружать содержимое или список?