--- 

# ПРУ 1 ausearch_process
# https://github.com/inspec/inspec/issues/1968
# ausearch --input-logs 
# Use the log file location from auditd.conf as input for searching
# -sv no | success status (yes|no)

    - block:

        - name: ПРУ 2 | ----
          become: yes
          command: sort -n "{{ playbook_dir }}/files/tmp/ad_user"  #Вывод отсортированного по алфавиту списка эталонных пользователей
          delegate_to: localhost
          register: var_get_ad_users # сохранение выводва в переменную
          tags:
            - ausearch_process

        - name: ПРУ 2 | Регистрация запуска/завершения процессов для пользователей из ad_user
          become: yes
          raw: |
              # echo "USER __________  '{{item}}'  __________"
              echo '                                                                           '
              echo '--------------------     PROCESS SUCCESS     --------------------         '
              echo '                                                                           '
              ausearch   -i --input-logs -sc 2519 -sv yes -ui $( id -u {{item}} ) | tail -n 19
              echo '                                                                           '
              echo '                                                                           '
              echo '--------------------     PROCESS FAILURE     --------------------         '
              echo '                                                                           '
              ausearch   -i --input-logs -sc 2519 -sv no -ui $( id -u {{item}} ) | tail -n 19
              echo '                                                                           '
              echo '                                                                           '
              echo ---------------------------- KILL SUCCESS ----------------------------
              echo '                                                                           '
              ausearch  -i --input-logs -sc kill -sv yes -ua $( id -u {{item}} ) | tail -n 19
              echo '                                                                           '
              echo '                                                                           '
              echo ---------------------------- KILL FAIL  ----------------------------
              echo '                                                                           '
              ausearch  -i --input-logs -sc kill -sv no -ua $( id -u {{item}} ) | tail -n 19
              echo '                                                                           '
              echo '                                                                           '
          loop: "{{var_get_ad_users.stdout_lines}}"
          failed_when: var_user_process.rc not in [0, 1] 
          register: var_user_process
          tags:
            - ausearch_process
            - write_log

        - name: ПРУ 2 | Регистрация запуска/завершения процессов
          debug: 
            msg: 
              - "---------------------------------"
              - " USER  =>   '{{item.item}}'   ----"
              - "----------------------------------"
              - "{{item.stdout_lines}}"
          loop: "{{var_user_process.results}}"
          loop_control:
            label: ""
          tags:
            - ausearch_process
            - write_log
            
        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'ausearch_process' %}{{ tg }}"
            task_res: "executed"
          tags:
            - ausearch_process

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'ausearch_process' %}{{ tgr }}"
          tags:
            - always