--- 
# ПУД 3  

    - block:

        - name: ПУД3 | ls
          become: yes
          raw: "ls -al /"
          failed_when: var_ls.rc not in [0, 1]
          register: var_ls
          tags:
            - ls

        - name: ПУД3 | печать ls
          debug: 
            msg: 
              - "{{ (var_ls.stdout_lines)}}"          # кол-во строк
          when: var_ls is defined
          tags:
            - ls

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'ls' %}{{ tg }}"
            task_res: "executed"
          tags:
            - ls

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'ls' %}{{tgr}}"
          tags:
            - always