--- 
# ПУД 3  

    - block:

        - name: ПУД3 |ps
          become: yes
          raw: "ps -ef | more "
          failed_when: var_ls.rc not in [0, 1]
          register: var_ps
          tags:
            - ps

        - name: ПУД3 | печать fdsik
          debug: 
            msg: 
              - "{{ (var_ps.stdout_lines)}}"          # кол-во строк
          when: var_ps is defined
          tags:
            - ps

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'ps' %}{{ tg }}"
            task_res: "executed"
          tags:
            - ps

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'ps' %}{{tgr}}"
          tags:
            - always