---

        - name: summary present (y/n)
          delegate_to: localhost 
          lineinfile: 
            path: "{{log_var}}"
            line: ""
            backrefs: yes
            regexp: '.*{{task_tag_rescue}}.*' 
          check_mode: yes
          ignore_errors: true
          register: var_presence
          tags:
            - always
            
        - name: replace line
          delegate_to: localhost
          register: var_replace
          lineinfile: 
            path: "{{log_var}}"
            regexp: '{{task_tag_rescue}}.*' 
            line: '{{"%-20s %15s" | format(task_tag_rescue + " => ", "error")}}'
            backrefs: yes
          when: var_presence.changed
          tags:
            - always

        - name: add line
          delegate_to: localhost
          lineinfile:
            dest: "{{log_var}}"
            line: '{{"%-20s %15s" | format(task_tag_rescue + " => ", "error")}}'
          when: not var_presence.changed
          tags:
            - always