--- 
# 10
    - name: ПРУ1 | проверка наличия журнала событий
      become: yes
      shell: "ls /var/log/audit"
      changed_when: false
      failed_when: false
      # ignore_errors: true
      register: var_audit_journal
      tags:
        - audit_journal

    - name: ПРУ1 | печать наличия журнала в /var/log/audit/
      debug: 
        msg: 
          # - "Total rows : {{ var_allowed_user_not_in_etalon | length }}" # вывод строк не содержащихся в эталонном файле
          # - "{{ (var_string_exists.stdout_lines != []) | ternary('',  '')}}"          # кол-во строк
          # - "{{ (var_string_exists.stdout != '0') | ternary('yes',  'no')}}"          # кол-во строк
          # - "found: {{ (var_dir_is_empty.stdout != [] ) | ternary('true',  'false')}}"          # кол-во строк
          - "----------  journal saerch  -------------"
          - "/var/log/audit/audit.log found => {{ (var_audit_journal.stdout_lines != []) | ternary('yes', 'no') }}"          # кол-во строк
          - "----------------------------------------------"
      ignore_errors: true
      when: var_audit_journal is defined
      tags:
        - audit_journal
