--- 
# --------------   Astra    -----------------

- name: Astra Linux (Debian) tasks
  hosts: all 
  gather_facts: false
  become: yes
  become_method: sudo

  pre_tasks:

    - name: logging settings update
      become: yes
      shell: 'find . -maxdepth 1 -name "*$(date +%Y%m%d_%H%M)*" | sed -i -r "s/^(log_path =).*/\1 $(echo "ansible_$(date "+%Y%m%d_%H%M")_$(wc -l).log")/" ansible.cfg' #запись имени лога с датой и временем запуска PLAYBOOK в конфигурационном файле (меняет имя лога в ansible.cfg)
      delegate_to: localhost
      tags:
        - always

    - name: include vars
      include_vars: "vars/{{ item }}.yml"
      loop:
        - "main"
        - "profile_vars"
      tags:
        - always

    - name: include profile_vars
      include_vars: vars/profile_vars.yml
      # when: ansible_os_family.startswith('Astra Linux') # переменные для Astra Linux
      tags:
        - always

    - name: Creates directory for logs
      become: yes
      delegate_to: localhost
      file:
        path: ./all_info/{{ansible_host}}/logs/
        state: directory
      tags:
        - always

    - name: Creates file for summary
      delegate_to: localhost
      file:
        path: ./all_info/{{ansible_host}}/logs/sum_{{ansible_host}}.txt
        state: touch
      tags:
        - always

    - name: Creates file for logs
      delegate_to: localhost
      file:
        path: ./all_info/{{ansible_host}}/logs/log_{{ansible_host}}.txt
        state: touch
        # mode: 0555
      tags:
        - always   

    - name: Creates file for logs
      delegate_to: localhost
      file:
        path: ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt
        state: touch
      tags:
        - always
  
  tasks: 

    - name: task krb5 1
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/1_krb5_1.yml
      tags:
        - krb5_1

    - name: task krb5 2
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/1_krb5_2.yml
      tags:
        - krb5_2

    - name: task ad_group_list
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/2.1_ad_group_list.yml
      tags:
        - ad_group_list

    - name: task ad_user_list
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/2.2_ad_user_list.yml
      tags:
        - ad_user_list

    - name: task loc_user_list
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/3.1_loc_user_list.yml
      tags:
        - loc_user_list

    - name: task loc_group_list
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/3.2_loc_group_list.yml
      tags:
        - loc_group_list

    - name: task wheel_1
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/6_wheel_1.yml
      tags:
        - wheel_1

    - name: task wheel_2
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/7_wheel_2.yml
      tags:
        - wheel_2

    - name: task include
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/15_include.yml
      tags:
        - include

    - name: task sudoersd
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/16_sudoersd.yml
      tags:
        - sudoersd


    - name: task sudo
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/sudo.yml
      tags:
        - sudo

    - name: task pw_quality_1
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/9_pw_quality_1.yml
      tags:
        - pw_quality_1

    - name: task pw_quality_2
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/12_pw_quality_2.yml
      tags:
        - pw_quality_2

    - name: task pw_quality_3
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/13_pw_quality_3.yml
      tags:
        - pw_quality_3

    - name: task pw_quality_4
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/10_pw_quality_4.yml
      tags:
        - pw_quality_4

    - name: task getfacl
      # ignore_errors: true
      include_tasks: ./tasks/PUD4/getfacl.yml
      tags:
        - getfacl


    - name: task aureport
      # ignore_errors: true
      include_tasks: ./tasks/PRU1/aureport.yml
      tags:
        - aureport


    - name: task common_password
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/11_common_password.yml
      tags:
        - common_password

    - name: task securetty
      # ignore_errors: true
      include_tasks: ./tasks/PUD1/19_securetty.yml
      tags:
        - securetty
        #  _____      ______)
        # |_____|    (----  )/-
        # |||  ||    /    / 
        # |||  ||     /______
        # |||  ||   /_______|
#

    - name: task ss
      # ignore_errors: true
      include_tasks: ./tasks/PUD2/ss.yml
      tags:
        - ss


        #  _____
        # |_____|   3333333
        # |||  ||      333
        # |||  ||     333 33
        # |||  ||   3333333
#

    - name: task ausearch_file
      # ignore_errors: true//
      include_tasks: ./tasks/PRU3/ausearch_file.yml
      tags:
        - ausearch_file

    # -------------------------

    # - name: task logrotate
    #   ignore_errors: true
    #   include_tasks: ./tasks/PRU1/logrotate.yml
    #   tags:
    #     - logrotate

    # -------------------------

    - name: task aureport_auth
      # ignore_errors: true
      include_tasks: ./tasks/PRU1/aureport_auth.yml
      tags:
        - aureport_auth

    - name: task auditd_status
      # ignore_errors: true
      include_tasks: ./tasks/PRU1/auditd_status.yml
      tags:
        - auditd_status

    - name: task auditctl
      # ignore_errors: true
      include_tasks: ./tasks/PRU1/auditctl.yml
      tags:
        - auditctl

    - name: task ausearch_process
      # ignore_errors: true
      include_tasks: ./tasks/PRU2/ausearch_process.yml
      tags:
        - ausearch_process

    - name: task swap
      # ignore_errors: true
      include_tasks: ./tasks/PRU4/swap.yml
      tags:
        - swap

    - name: task ksn
      # ignore_errors: true
      include_tasks: ./tasks/PRU5/ksn.yml
      tags:
        - ksn

    - name: task aide_cron
      # ignore_errors: true
      include_tasks: ./tasks/PRU5/aide_cron.yml
      tags:
        - aide_cron

    - name: task aide_conf
      # ignore_errors: true
      include_tasks: ./tasks/PRU5/aide_conf.yml
      tags:
        - aide_conf

# proflie section

    - name: task pr_password_quality_1
      # ignore_errors: true
      include_tasks: ./tasks/profiles/pr_password_quality_1.yml
      tags:
        - pr_password_quality_1

    - name: task pr_password_quality_2
      # ignore_errors: true
      include_tasks: ./tasks/profiles/pr_password_quality_2.yml
      tags:
        - pr_password_quality_2

    - name: task pr_password_quality_3
      # ignore_errors: true
      include_tasks: ./tasks/profiles/pr_password_quality_3.yml
      tags:
        - pr_password_quality_3

    - name: task pr_mask
      # ignore_errors: true
      include_tasks: ./tasks/profiles/pr_mask.yml
      tags:
        - pr_mask

    - name: task pr_astra_console
      # ignore_errors: true
      include_tasks: ./tasks/profiles/pr_astra_console.yml
      tags:
        - pr_astra_console

    - name: task pr_sysctl
      # ignore_errors: true
      include_tasks: ./tasks/profiles/pr_sysctl.yml
      tags:
        - pr_sysctl

    - name: task pr_screen
      # ignore_errors: true
      include_tasks: ./tasks/profiles/pr_screen.yml
      tags:
        - pr_screen

    # - name: task fetch_files
    #   include_tasks: ./tasks/fetch_files.yml
    #   tags:
    #     - fetch_files

    - name: task fetch
      include_tasks: ./tasks/fetch.yml
      loop: "{{ files_to_fetch_var }}"
      tags:
        - fetch

  post_tasks:

    # - name: playbook summary
    #   shell: 'find . -maxdepth 1 -name "*$(date +%Y%m%d_%H%M)*" | sed -i -r "s/^(log_path =).*/\1 $(echo "ansible_$(date "+%Y%m%d_%H%M")_$(wc -l).log")/" ansible.cfg'
    #   delegate_to: localhost
    #   tags:
    #     - always

    # - name: summary parsing
    #   shell: 'find . -maxdepth 1 -name "*$(date +%Y%m%d_%H%M)*" | sed -i -r "s/^(log_path =).*/\1 $(echo "ansible_$(date "+%Y%m%d_%H%M")_$(wc -l).log")/" ansible.cfg'
    #   delegate_to: localhost
    #   tags:
    #     - always

    - name: sort summary file by status
      shell: 'sort -r -k 3,3 -o ./all_info/{{ansible_host}}/logs/sum_{{ansible_host}}.txt ./all_info/{{ansible_host}}/logs/sum_{{ansible_host}}.txt' #запись имени лога с датой и временем запуска PLAYBOOK в конфигурационном файле (меняет имя лога в ansible.cfg)
      delegate_to: localhost
      tags:
        - always

    - name: sort summary file by status
      shell: 'sort -r -k 3,3 -o ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt' #запись имени лога с датой и временем запуска PLAYBOOK в конфигурационном файле (меняет имя лога в ansible.cfg)
      delegate_to: localhost
      tags:
        - always


    # sort -k3 -n -o sum_localhost.txt{,}