--- 
# ПРУ 1 ausearch_process
# https://github.com/inspec/inspec/issues/768
# ausearch --input-logs 
# Use the log file location from auditd.conf as input for searching
# -sv no | success status (yes|no)

    - name: ПРУ3 | ausearch_process
      become: yes
      command: sort -n "{{ playbook_dir }}/files/tmp/local_user_list"  #Вывод отсортированного по алфавиту списка эталонных пользователей
      changed_when: false
      failed_when: false
      delegate_to: localhost
      ignore_errors: true 
      register: var_get_userlist # сохранение выводва в переменную
      tags:
        - ausearch_process
# -sv no 
    - name: ПРУ3 | Сохранение списка пользователей в переменную
      become: yes
      shell:
        cmd: |
          echo '                                                                           '
          echo '                                                                           '
          echo ---------------------------- ALL EXECUTIONS  ----------------------------
          echo '                                                                           '
          ausearch  -i --input-logs -m execve -ui $( id -u {{item}} ) | tail -n 7
          echo '                                                                           '
          echo '                                                                           '
          echo ---------------------------- ACCESS SUCCESS ----------------------------
          echo '                                                                           '
          ausearch  -i --input-logs -sc 257 -sv yes -ui $( id -u {{item}} ) | tail -n 7
          echo '                                                                           '
          echo '                                                                           '
          echo '   --------------------     ACCESS FAILURE     --------------------   '
          echo '                                                                           '
          ausearch   -i --input-logs -sc 257 -sv no -ui $( id -u {{item}} ) | tail -n 7
      changed_when: false
      failed_when: false
      loop: "{{var_get_userlist.stdout_lines}}"
      # ignore_errors: true
      # args:
      #   executable: /bin/bash
      register: var_user_auth
      tags:
        - ausearch_process
        - write_log

    - name: ПРУ3 | печать пользователей
      debug: 
        msg: 
          - "---------------------------------"
          - "----------   '{{item.item}}'   ----------"
          - "----------------------------------"
          - "{{item.stdout_lines}}"
      ignore_errors: true
      # loop: "{{ | debug}}"
      loop: "{{var_user_auth.results}}"
      # loop: "{{(var_user_audit)[:] | selectattr('stdout', '!=', '\'\'') | map(attribute='stdout') | list}}"
      # when: var_get_userlist is defined
      tags:
       - ausearch_process
       