--- 
# 10
    - name: ПРУ1 | проверка наличия logrotate в cron
      become: yes
      shell: "cd /etc/cron.daily/ | if egrep  -q ^logrotate$; then echo yes; else echo no; fi"
      changed_when: false
      failed_when: false
      # ignore_errors: true
      register: var_logrotate
      tags:
        - logrotate

    - name: ПРУ1 | печать что директория пустая
      debug: 
        msg: 
          # - "Total rows : {{ var_allowed_user_not_in_etalon | length }}" # вывод строк не содержащихся в эталонном файле
          # - "{{ (var_string_exists.stdout_lines != []) | ternary('',  '')}}"          # кол-во строк
          # - "{{ (var_string_exists.stdout != '0') | ternary('yes',  'no')}}"          # кол-во строк
          # - "found: {{ (var_dir_is_empty.stdout != [] ) | ternary('true',  'false')}}"          # кол-во строк
          - "logrotate active: {{ (var_logrotate.stdout) }}"          # кол-во строк
      ignore_errors: true
      when: var_logrotate is defined
      tags:
        - logrotate
