--- 
# ПРУ 1 статус

    - name: ПРУ4 |  статус auditd
      become: yes
      shell: "systemctl is-active auditd || true"
      changed_when: false
      failed_when: false
      # ignore_errors: true
      register: var_status
      tags:
        - auditd_status

    - name: ПРУ4 |  статус auditd
      debug: 
        msg: 
          - "----------------auditd status----------------"
          - " auditd status =>  {{(var_status.stdout)}}"
          - "---------------------------------------------"
      ignore_errors: true
      when: var_status is defined
      tags:
        - auditd_status
        - write_log
