    - name: Сбор /etc/krb5.conf
      shell: if test -f "/etc/krb5.conf" ; then /bin/true; else /bin/false; fi
      register: result
      ignore_errors: True
      tags:
       - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/krb5.conf => ' 'false' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when: result is failed
      tags:
        - fetch_files

    - name: ПУД1 | загрузка файла /etc/krb5.conf
      fetch:
        flat: yes
        validate_checksum: true
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/krb5.conf"
      register: result_fetch
      when: result is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/krb5.conf => ' 'true' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/krb5.conf => ' 'error' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is failed
      tags:
        - fetch_files


    - name: Сбор /etc/sssd/sssd.conf
      shell: if test -f "/etc/sssd/sssd.conf" ; then /bin/true; else /bin/false; fi
      register: result
      ignore_errors: True
      tags:
       - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/sssd/sssd.conf => ' 'false' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when: result is failed
      tags:
        - fetch_files

    - name: ПУД1 | загрузка файла /etc/sssd/sssd.conf
      fetch:
        flat: yes
        validate_checksum: true
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/sssd/sssd.conf"
      register: result_fetch
      when: result is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/sssd/sssd.conf => ' 'true' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/sssd/sssd.conf => ' 'error' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is failed
      tags:
        - fetch_files


    - name: Сбор /etc/group
      shell: if test -f "/etc/group" ; then /bin/true; else /bin/false; fi
      register: result
      ignore_errors: True
      tags:
       - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/group => ' 'false' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when: result is failed
      tags:
        - fetch_files

    - name: ПУД1 | загрузка файла /etc/group
      fetch:
        flat: yes
        validate_checksum: true
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/group"
      register: result_fetch
      when: result is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/group => ' 'true' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/group => ' 'error' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is failed
      tags:
        - fetch_files

    - name: Сбор /etc/pam.d/su
      shell: if test -f "/etc/pam.d/su" ; then /bin/true; else /bin/false; fi
      register: result
      ignore_errors: True
      tags:
       - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/pam.d/su => ' 'false' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when: result is failed
      tags:
        - fetch_files

    - name: ПУД1 | загрузка файла /etc/pam.d/su
      fetch:
        flat: yes
        validate_checksum: true
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/pam.d/su"
      register: result_fetch
      when: result is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/pam.d/su => ' 'true' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/pam.d/su => ' 'error' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is failed
      tags:
        - fetch_files

    - name: Сбор /etc/security/pwquality.conf
      shell: if test -f "/etc/security/pwquality.conf" ; then /bin/true; else /bin/false; fi
      register: result
      ignore_errors: True
      tags:
       - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/security/pwquality.conf => ' 'false' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when: result is failed
      tags:
        - fetch_files

    - name: ПУД1 | загрузка файла /etc/security/pwquality.conf
      fetch:
        flat: yes
        validate_checksum: true
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/security/pwquality.conf"
      register: result_fetch
      when: result is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/security/pwquality.conf => ' 'true' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/security/pwquality.conf => ' 'error' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is failed
      tags:
        - fetch_files

    - name: Сбор /etc/login.defs
      shell: if test -f "/etc/login.defs" ; then /bin/true; else /bin/false; fi
      register: result
      ignore_errors: True
      tags:
       - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/login.defs => ' 'false' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when: result is failed
      tags:
        - fetch_files

    - name: ПУД1 | загрузка файла /etc/login.defs
      fetch:
        flat: yes
        validate_checksum: true
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/login.defs"
      register: result_fetch
      when: result is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/login.defs => ' 'true' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/login.defs => ' 'error' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is failed
      tags:
        - fetch_files

    - name: Сбор /etc/pam.d/common-password
      shell: if test -f "/etc/pam.d/common-password" ; then /bin/true; else /bin/false; fi
      register: result
      ignore_errors: True
      tags:
       - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/pam.d/common-password => ' 'false' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when: result is failed
      tags:
        - fetch_files

    - name: ПУД1 | загрузка файла /etc/pam.d/common-password
      fetch:
        flat: yes
        validate_checksum: true
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/pam.d/common-password"
      register: result_fetch
      when: result is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/pam.d/common-password => ' 'true' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/pam.d/common-password => ' 'error' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is failed
      tags:
        - fetch_files

    - name: Сбор /etc/sudoers
      shell: if test -f "/etc/sudoers" ; then /bin/true; else /bin/false; fi
      register: result
      ignore_errors: True
      tags:
       - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/sudoers => ' 'false' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when: result is failed
      tags:
        - fetch_files

    - name: ПУД1 | загрузка файла /etc/sudoers
      fetch:
        flat: yes
        validate_checksum: true
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/sudoers"
      register: result_fetch
      when: result is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/sudoers => ' 'true' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/sudoers => ' 'error' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is failed
      tags:
        - fetch_files

    # - name: Сбор /etc/sudoers.d
    #   shell: if test -f "/etc/sudoers.d" ; then /bin/true; else /bin/false; fi
    #   register: result
    #   ignore_errors: True
    #   tags:
    #    - fetch_files

    # - name: fetch stat +
    #   shell: "printf '%-35s %15s\n' '/etc/sudoers.d => ' 'false' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
    #   delegate_to: localhost
    #   when: result is failed
    #   tags:
    #     - fetch_files

    # - name: ПУД1 | загрузка файла /etc/sudoers.d
    #   fetch:
    #     flat: yes
    #     validate_checksum: true
    #     dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
    #     src: "/etc/sudoers.d"
    #   register: result_fetch
    #   when: result is success
    #   tags:
    #     - fetch_files

    # - name: fetch stat +
    #   shell: "printf '%-35s %15s\n' '/etc/sudoers.d => ' 'true' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
    #   delegate_to: localhost
    #   when:
    #     - result is success
    #     - result_fetch is success
    #   tags:
    #     - fetch_files

    # - name: fetch stat +
    #   shell: "printf '%-35s %15s\n' '/etc/sudoers.d => ' 'error' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
    #   delegate_to: localhost
    #   when:
    #     - result is success
    #     - result_fetch is failed
    #   tags:
    #     - fetch_files

    - name: Сбор /etc/passwd
      shell: if test -f "/etc/passwd" ; then /bin/true; else /bin/false; fi
      register: result
      ignore_errors: True
      tags:
       - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/passwd => ' 'false' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when: result is failed
      tags:
        - fetch_files

    - name: ПУД1 | загрузка файла /etc/passwd
      fetch:
        flat: yes
        validate_checksum: true
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/passwd"
      register: result_fetch
      when: result is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/passwd => ' 'true' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/passwd => ' 'error' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is failed
      tags:
        - fetch_files

    - name: Сбор /etc/securetty
      shell: if test -f "/etc/securetty" ; then /bin/true; else /bin/false; fi
      register: result
      ignore_errors: True
      tags:
       - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/securetty => ' 'false' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when: result is failed
      tags:
        - fetch_files

    - name: ПУД1 | загрузка файла /etc/securetty
      fetch:
        flat: yes
        validate_checksum: true
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/securetty"
      register: result_fetch
      when: result is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/securetty => ' 'true' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/securetty => ' 'error' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is failed
      tags:
        - fetch_files

    - name: Сбор /etc/shadow
      shell: if test -f "/etc/shadow" ; then /bin/true; else /bin/false; fi
      register: result
      ignore_errors: True
      tags:
       - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/shadow => ' 'false' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when: result is failed
      tags:
        - fetch_file

    - name: ПУД1 | загрузка файла /etc/shadow
      fetch:
        flat: yes
        validate_checksum: true
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/shadow"
      register: result_fetch
      when: result is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/shadow => ' 'true' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/shadow => ' 'error' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is failed
      tags:
        - fetch_files

    - name: Сбор /etc/passwd
      shell: if test -f "/etc/passwd" ; then /bin/true; else /bin/false; fi
      register: result
      ignore_errors: True
      tags:
       - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/passwd => ' 'false' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when: result is failed
      tags:
        - fetch_files

    - name: ПУД1 | загрузка файла /etc/passwd
      fetch:
        flat: yes
        validate_checksum: true
        dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        src: "/etc/passwd"
      register: result_fetch
      when: result is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/passwd => ' 'true' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is success
      tags:
        - fetch_files

    - name: fetch stat +
      shell: "printf '%-35s %15s\n' '/etc/passwd => ' 'error' | tee -a ./all_info/{{ansible_host}}/logs/fetch_stat_{{ansible_host}}.txt"
      delegate_to: localhost
      when:
        - result is success
        - result_fetch is failed
      tags:
        - fetch_files
