--- 
# ПУД 4 матрица доступов

    - name: ПУД1 | запись групп 
      become: yes
      shell: "getfacl –R (subject name from ТПР by auditor choice "
      changed_when: false
      failed_when: false
      # ignore_errors: true
      register: var_permissions_matrix
      tags:
        - permissions_matrix

    - name: ПУД1 | печать сетевых содинений
      debug: 
        msg: 
          # - "Total rows : {{ var_allowed_user_not_in_etalon | length }}" # вывод строк не содержащихся в эталонном файле
          # - "{{ (var_string_exists.stdout_lines != []) | ternary('',  '')}}"          # кол-во строк
          # - "{{ (var_string_exists.stdout != '0') | ternary('yes',  'no')}}"          # кол-во строк
          # - "found: {{ (var_dir_is_empty.stdout != [] ) | ternary('true',  'false')}}"          # кол-во строк
          - "{{ (var_permissions_matrix.stdout_lines)}}"          # кол-во строк
      ignore_errors: true
      when: var_permissions_matrix is defined
      tags:
        - permissions_matrix
