---
    - block:

        - name: ПРУ 4 | проверка, что файл "/etc/cron.daily/swap_wipe" есть
          become: yes
          raw: "test -f /etc/cron.daily/swap_wipe"
          failed_when: var_file_exists.rc not in [0, 1]
          register: var_file_exists
          tags:
            - swap

        - name: ПРУ 4 | печать, что файл "/etc/cron.daily/swap_wipe" есть
          debug: 
            msg:
              - "{{ not var_file_exists.rc | bool }}"
          tags:
            - swap

        - name: ПРУ 4 | чтение swap_wipe эталона
          become: yes
          raw: "cat ./files/tmp/swap_wipe"
          delegate_to: localhost
          register: var_swap_etalon
          tags:
            - swap

        - name: ПРУ 4 | чтение swap_wipe хоста
          become: yes
          raw: "cat /etc/cron.daily/swap_wipe"
          failed_when: var_swap_dest.rc not in [0, 1]
          register: var_swap_dest
          tags:
            - swap

        - name: результат прохождения проверок
          set_fact:
            var_swap_difference: "{% set var_swap_diff = ( var_swap_etalon.stdout_lines)[2:] | difference(var_swap_dest.stdout_lines ) %}{{var_swap_diff}}"
          tags:
            - swap

        - name: ПРУ 4 | печать diff
          debug: 
            msg:
              # - "{{ var_swap_dest.stdout_lines }}"
              # - "-----------------------------------"
              # - "{{ var_swap_difference  == [] }}"
              # - "-----------------------------------"
              - "{{ var_swap_difference }}"
          tags: 
            - swap

        - name: результат прохождения проверок
          set_fact:
            task_result: "{% set passed = ( var_swap_difference  == [] ) %}{{ passed }}"
          tags:
            - swap

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'swap' %}{{ tg }}"
            task_res: "{{ task_result }}"
          tags:
            - swap

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'swap' %}{{ tgr }}"
          tags:
            - always