--- 
# --------------   Astra    -----------------
# - name: main tasks
#   hosts: local 
#   gather_facts: false 
#   ignore_errors: true
#   remote_user: ansibenode
#   become: yes
#   become_method: sudo
#     pre_tasks:
  
- name: main tasks
  hosts: all 
  gather_facts: true 
  ignore_errors: true
  # remote_user: ansibenode
  become: yes
  become_method: sudo
  # remote_user: root
  pre_tasks:
    - name: logging settings update
      shell: 'find . -maxdepth 1 -name "*$(date +%Y%m%d_%H%M)*" | sed -i -r "s/^(log_path =).*/\1 $(echo "ansible_$(date "+%Y%m%d_%H%M")_$(wc -l).log")/" ansible.cfg' #запись имени лога с датой и временем запуска PLAYBOOK в конфигурационном файле (меняет имя лога в ansible.cfg)
      delegate_to: localhost
      # run_once: true
      # remote_user: root
      tags:
        - always # запуск независимо от тега
      
  tasks: 

    # - name: logfile name setting
    #   shell: 'find . -maxdepth 1 -name "*$(date +%Y%m%d_%H%M)*" | sed -i -r "s/^(log_path =).*/\1 $(echo "ansible_$(date "+%Y%m%d_%H%M")_$(wc -l).log")/" ansible.cfg' #запись имени лога с датой и временем запуска PLAYBOOK в конфигурационном файле (меняет имя лога в ansible.cfg)
    #   # remote_user: root
    #   tags:
    #     - always # запуск независимо от тега

    - name: include vars
      include_vars: vars/main.yml
      # when: ansible_os_family.startswith('Astra Linux') # переменные для Astra Linux
      tags:


# ------- пуд 1

        - krb5_1
        - krb5_2
        - ad_group_list
        - ad_user_list
        - loc_user_list
        - loc_group_list
        - wheel_1
        - wheel_2
        - include
        - sudoersd
        - system_auth
        - pw_quality_1
        - pw_quality_2
        - pw_quality_3
        - pw_quality_4
        - sudo

# ------- пуд 2

        - ss

# ------- пуд 3

        - fdisk
        - ls
        - ps

# ------- пуд 4

        - getfacl

# ------- test

        - info_gathering

# ------- ПРУ 1

        - auditd_status

        - logrotate
        - 1.2.1.07
        - 1.2.1.08
        - 1.2.1.10
        - 1.2.1.11
        - 1.2.1.12
        - fetch

    - name: task krb5 1
      ignore_errors: true
      include_tasks: tasks/PUD1/1_krb5_1.yml
      tags:
        - krb5_1

    - name: task krb5 2
      ignore_errors: true
      include_tasks: tasks/PUD1/1_krb5_2.yml
      tags:
        - krb5_2

    - name: task ad_group_list
      ignore_errors: true
      include_tasks: tasks/PUD1/2.1_ad_group_list.yml
      tags:
        - ad_group_list

    - name: task ad_user_list
      ignore_errors: true
      include_tasks: tasks/PUD1/2.2_ad_user_list.yml
      tags:
        - ad_user_list

    - name: task loc_user_list
      ignore_errors: true
      include_tasks: tasks/PUD1/3.1_loc_user_list.yml
      tags:
        - loc_user_list

    - name: task loc_group_list
      ignore_errors: true
      include_tasks: tasks/PUD1/3.2_loc_group_list.yml
      tags:
        - loc_group_list

    - name: task wheel_1
      ignore_errors: true
      include_tasks: tasks/PUD1/6_wheel_1.yml
      tags:
        - wheel_1

    - name: import task wheel_1
      import_tasks: tasks/PUD1/6_wheel_1.yml
      when:  tag_name == "wheel_1"
      delegate_to: localhost
      
      # ignore_errors: true
      # include_tasks: tasks/PUD1/6_wheel_1.yml
      # tags:
      #   - wheel_1

    - name: task wheel_2
      ignore_errors: true
      include_tasks: tasks/PUD1/7_wheel_2.yml
      tags:
        - wheel_2

    - name: task include
      ignore_errors: true
      include_tasks: tasks/PUD1/15_include.yml
      tags:
        - include

    - name: task sudoersd
      ignore_errors: true
      include_tasks: tasks/PUD1/16_sudoersd.yml
      tags:
        - sudoersd

    - name: task sudo
      ignore_errors: true
      include_tasks: tasks/PUD1/sudo.yml
      tags:
        - sudo

    - name: task pw_quality_1
      ignore_errors: true
      include_tasks: tasks/PUD1/9_pw_quality_1.yml
      tags:
        - pw_quality_1

    - name: task pw_quality_2
      ignore_errors: true
      include_tasks: tasks/PUD1/12_pw_quality_2.yml
      tags:
        - pw_quality_2

    - name: task pw_quality_3
      ignore_errors: true
      include_tasks: tasks/PUD1/13_pw_quality_3.yml
      tags:
        - pw_quality_3

    - name: task pw_quality_4
      ignore_errors: true
      include_tasks: tasks/PUD1/10_pw_quality_4.yml
      tags:
        - pw_quality_4

    - name: task getfacl
      ignore_errors: true
      include_tasks: tasks/PUD4/getfacl.yml
      tags:
        - getfacl

    - name: task auditd_status
      ignore_errors: true
      include_tasks: tasks/PRU1/auditd_status.yml
      tags:
        - auditd_status

    - name: task aureport
      ignore_errors: true
      include_tasks: tasks/PRU1/aureport.yml
      tags:
        - aureport

    - name: task system_auth
      ignore_errors: true
      include_tasks: tasks/PUD1/11_system_auth.yml
      tags:
        - system_auth

    - name: task info_gathering
      ignore_errors: true
      include_tasks: tasks/info_gathering.yml
      tags:
        - info_gathering

    - name: task ss
      ignore_errors: true
      include_tasks: tasks/PUD2/ss.yml
      tags:
        - ss

    - name: task logrotate
      ignore_errors: true
      include_tasks: tasks/PRU1/logrotate.yml
      tags:
        - logrotate

    - name: task fdsik
      ignore_errors: true
      include_tasks: tasks/PUD3/fdsik.yml
      tags:
        - fdisk

    - name: task ls
      ignore_errors: true
      include_tasks: tasks/PUD3/ls.yml
      tags:
        - ls

    - name: task ps
      ignore_errors: true
      include_tasks: tasks/PUD3/ps.yml
      tags:
        - ps