---
        - name: summary present (y/n)
          delegate_to: localhost 
          lineinfile: 
            path: "{{log_var}}"
            line: ""
            backrefs: yes
            regexp: '.*{{task_tag}}.*' 
          check_mode: yes
          ignore_errors: true
          register: var_presence
          tags:
            - always

        - name: summary verfication
          delegate_to: localhost
          register: var_verfication
          lineinfile: 
            path: "{{log_var}}"
            regexp: '.*{{task_tag}}.*' 
            line: '{{"%-20s %15s" | format(task_tag + " => ", task_res)}}'
            backrefs: yes
          when: var_presence.changed
          tags:
            - always

        - name: summary +
          shell: "printf '%-20s %15s\n' '{{task_tag}} => ' {{ task_res }} | tee -a {{log_var}}"
          delegate_to: localhost
          when: not var_presence.changed
          tags:
            - always