---
    - block:
    
        - name: ПУД 1 | проверка, что файл "/etc/krb5.conf" есть
          become: yes
          raw: "test -f /etc/krb5.conf"
          failed_when: var_file_exists.rc
          register: var_file_exists
            - krb5_1

        - name: ПУД 1 | save наличие строки "default_realm = ROSNEFT.RU"
          become: yes
          raw: 'egrep "^[[:space:]]*#*[[:space:]]*default_realm[[:space:]]*=[[:space:]]*ROSNEFT\.RU[[:space:]]*$" /etc/krb5.conf'
          failed_when: var_krb5.rc not in [0, 1] # код результата исполнения 0 - пройдена, 1 - не пройдена, 2 - файл не найден , вызов исключнеия если не 0 или 1
          register: var_krb5
          tags:
            - krb5_1

        - name: ПУД 1 | проверка наличия строки "default_realm = ROSNEFT.RU"
          debug:
            msg:
              - "  "
              - "----------------------------------------------------  "
              - "[default_realm = ROSNEFT.RU] существует => {{ (not var_krb5.rc) | ternary('да', 'нет') }}         "          # кол-во строк
              - "----------------------------------------------------  "
          tags:
            - krb5_1
            - write_log

        - name: ПУД 1 | проверка активности строки "default_realm = ROSNEFT.RU"
          become: yes
          raw: 'egrep "^[[:space:]]*default_realm[[:space:]]*=[[:space:]]*ROSNEFT\.RU[[:space:]]*$" /etc/krb5.conf'
          failed_when: var_krb5_active.rc not in [0, 1]
          register: var_krb5_active
          tags:
            - krb5_1

        - name: ПУД 1 | проверка активности строки "default_realm = ROSNEFT.RU"
          debug: 
            msg: 
              - "  "
              - "-----------------------------------------------------  "
              - "[default_realm = ROSNEFT.RU] активна => {{ (not var_krb5_active.rc) | ternary('да', 'нет') }}           "          # кол-во строк
              - "-----------------------------------------------------  "
          # when: var_krb5 is defined
          tags:
            - krb5_1
            - write_log

        - name: результат прохождения проверок
          set_fact:
            task_result: "{% set passed = ( not var_krb5_active.rc ) %}{{passed}}"
          tags:
            - krb5_1

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'krb5_1' %}{{ tg }}"
            task_res: "{{ task_result }}"
          tags:
            - krb5_1

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'krb5_1' %}{{tgr}}"
          tags:
            - always