---
    - block:

        - name: ПУД1 | проверка, что файл "/etc/sssd/sssd.conf" есть
          become: yes
          raw: "test -f /etc/sssd/sssd.conf"
          failed_when: var_file_exists.rc
          register: var_file_exists
          tags:
            - krb5_2

        - name: ПУД1 | save наличие строки "krb5_realm = ROSNEFT.RU"
          become: yes
          raw: 'egrep "^[[:space:]]*#*[[:space:]]*krb5_realm[[:space:]]*=[[:space:]]*ROSNEFT\.RU[[:space:]]*$" /etc/sssd/sssd.conf'
          failed_when: var_krb5.rc not in [0, 1]
          register: var_krb5
          tags:
            - krb5_2

        - name: ПУД1 | проверка наличия строки "krb5_realm = ROSNEFT.RU" в /etc/sssd/sssd.conf
          debug:
            msg: 
              - "  "
              - "----------------------------------------------------  "
              - "[krb5_realm = ROSNEFT.RU] существует => {{ ( not var_krb5.rc) | ternary('да', 'нет') }}         "          # кол-во строк
              - "----------------------------------------------------  "
          # when: var_krb5 is defined
          tags:
            - krb5_2
            - write_log

        - name: ПУД1 | проверка "активности строки krb5_realm = ROSNEFT.RU"
          become: yes
          raw: 'egrep "^[[:space:]]*krb5_realm[[:space:]]*=[[:space:]]*ROSNEFT\.RU[[:space:]]*$" /etc/sssd/sssd.conf'
          failed_when: var_krb5_active is search('Нет такого файла или каталога')
          register: var_krb5_active
          tags:
            - krb5_2

        - name: ПУД1 | проверка активности строки "krb5_realm = ROSNEFT.RU" в /etc/sssd/sssd.conf
          debug: 
            msg: 
              - "  "
              - "-----------------------------------------------------  "
              - "[krb5_realm = ROSNEFT.RU] активна => {{ ( not var_krb5_active.rc ) | ternary( 'да', 'нет' )}}           "          # кол-во строк
              - "-----------------------------------------------------  "
          # when: var_krb5 is defined
          tags:
            - krb5_2
            - write_log

        - name: результат прохождения проверок
          set_fact:
            task_result: "{% set passed = ( not var_krb5_active.rc ) %}{{passed}}"
          tags:
            - krb5_2

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'krb5_2' %}{{ tg }}"
            task_res: "{{ task_result }}"
          tags:
            - krb5_2

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'krb5_2' %}{{tgr}}"
          tags:
            - always
