---
    - block:

        - name: ПРУ 5 | Проверка aide_cron в cron.daily
          become: yes
          raw: "ls /etc/cron.daily/ | more | grep ^aide_cron$"
          failed_when: var_aide_cron.rc not in [0, 1] 
          register: var_aide_cron
          tags:
            - aide_cron

        - name: ПРУ 5 | проверка aide_cron
          debug:
            msg: 
              - "     "
              - "--------------------- проверка aide_cron  --------------------"
              - " aide_cron Есть => {{(not var_aide_cron.rc ) | ternary('да', 'нет') }}"
              - "--------------------------------------------------------"
          tags:      no_log: true

            - aide_cron
            - write_log

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'aide_cron' %}{{ tg }}"
            task_res: "executed"
          tags:
            - aide_cron

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'aide_cron' %}{{tgr}}"
          tags:
            - always