---
    - block:

        - name: ПРУ 5 | проверка aide_cron
          debug:
            msg: 
              - "     "
              - "--------------------- проверка aide_cron  --------------------"
              - " aide_cron Есть => {{(not var_aide_conf.rc ) | ternary('да', 'нет') }}"
              - "--------------------------------------------------------"
          tags:
            - aide_conf
            - write_log

        # - name: ПРУ 5 | загрузка файла /etc/sssd/sssd.conf
        #   fetch:
        #     flat: yes
        #     dest: "{{playbook_dir}}/all_info/{{ansible_ssh_host}}/"
        #     src: "/etc/aide.conf"
        #   tags:
        #     - aide_conf

        # - name: summary +
        #   shell: "printf '%-20s %15s\n' 'ksn => ' {{(var_aide_cron.stdout_lines != []) | ternary('1', '0')}} | tee -a  {{log_var}}"
        #   delegate_to: localhost
        #   tags:
        #     - aide_conf

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'aide_conf' %}{{ tg }}"
            task_res: "executed"
          tags:
            - aide_conf

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'aide_conf' %}{{tgr}}"
          tags:
            - always