---
    - block:

        - name: ПРУ5 | Получение времени последнего времени актуализции базы данных вирусных сигнатур
          become: yes
          shell: "$(echo /opt/kaspersky/kesl/bin/kesl-control --app-info) | egrep -i '^[[:space:]]*Защита[[:space:]]*от[[:space:]]*файловых[[:space:]]*угроз:[[:space:]]*Задача[[:space:]]*доступна[[:space:]]*и[[:space:]]*выполняется[[:space:]]*$'"
          failed_when: var_aide_cron.rc not in [0, 1] 
          register: var_ksn
          tags:
            - ksn_synch

        - name: ПРУ5 | Печать "время последней актуализации БД вирусных сигнатур"
          debug:
            msg: 
              - "     "
              - "--------------------------------------------------------"
              - " ФЗ активна {{( not var_ksn.rc ) | ternary('да', 'нет') }}"
              - "--------------------------------------------------------"
          ignore_errors: true
          tags:
            - ksn_synch
            - write_log

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'ksn_synch' %}{{ tg }}"
            task_res: "executed"
          tags:
            - ksn_synch

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'ksn_synch' %}{{tgr}}"
          tags:
            - always