---

    - block:

        - name: ПР | проверка, что файл "/parsecfs/mode_mask" есть
          become: yes
          raw: "test -f /parsecfs/mode_mask"
          failed_when: var_file_exists.rc
          register: var_file_exists
          tags:
            - pr_mask
 
        - name: ПР | проверка параметров "/parsecfs/mode_mask"
          become: yes
          raw: "egrep '0000' /parsecfs/mode_mask"
          failed_when: var_pr_mask.rc not in [0, 1]
          register: var_pr_mask
          tags:
            - pr_mask

        - name: ПР | параметр /parsecfs/mode_mask = '0000'
          debug:
            msg: 
              - "  "
              - "------------------------------|||---------------------  "
              - " /parsecfs/mode_mask = '0000' => {{ ( not var_pr_mask.rc ) | ternary('да', 'нет') }}"
              - "------------------------------^^----------------------  "
          tags:
            - pr_mask
            - write_log

        - name: результат прохождения проверок
          set_fact:
            task_result: "{% set passed = ( not var_pr_mask.rc ) %}{{passed}}"
          tags:
            - pr_mask

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set tg = 'pr_mask' %}{{ tg }}"
            task_res: "{{ task_result }}"
          tags:
            - pr_mask

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set tgr = 'pr_mask' %}{{tgr}}"
          tags:
            - always