--- 
    - block:

        - name: ПР | проверка, что файл "/etc/sysctl.conf" есть
          become: yes
          raw: "test -f /etc/sysctl.conf"
          failed_when: var_file_exists.rc
          register: var_file_exists
            - pr_sysctl

        - name: ПР | проверка параметров "/etc/sysctl.conf"
          become: yes
          raw: 'egrep ".*kernel\.sysrq[[:space:]]*=[[:space:]]*0.*$" /etc/sysctl.conf'
          failed_when: var_pr_sysctl.rc not in [0, 1] 
          register: var_pr_sysctl
          tags:
            - pr_sysctl

        - name: ПР | Проверка совпадения параметров "/etc/sysctl.conf"  с эталонныим значениями
          debug:
            msg: 
              - "  "
              - "------------------------------------------------------  "
              - " kernel.sysrq=0' => {{ ( not var_pr_sysctl.rc ) | ternary('да', 'нет') ) }}"
              - "------------------------------------------------------  "
          tags:
            - pr_sysctl
            - write_log
          
        - name: результат прохождения проверок
          set_fact:
            task_result: "{% set passed = ( not var_pr_sysctl.rc ) %}{{ passed }}"
          tags:
            - pr_sysctl

        - include_tasks: ../summary/sum.yml
          vars:
            task_tag: "{% set var_tag = 'pr_sysctl' %}{{ var_tag }}"
            task_res: "{{ task_result }}"
          tags:
            - pr_sysctl

      rescue:

        - include_tasks: ../summary/rescue.yml
          vars:
            task_tag_rescue: "{% set var_resuce = 'pr_sysctl' %}{{  var_resuce }}"
          tags:
            - always